CheckM  version 1.1.3 easyconfig file
ubccr/software-layer pull request #188
Opened 2024-01-19 22:32 UTC by tonykew

CheckM  version 1.1.3

Tony

2024-01-20 04:59 UTC, aebruno requested changes

2024-01-20 04:59 UTC, aebruno commented on config/easybuild/easyconfigs/CheckM-1.1.3-foss-2021b.eb
> +     'ln -s "/util/software/data/%%(name)s/%s" "%%(installdir)s/data"' % ( local_checkm_database_version ),
Let's remove this symlink as we already set the `CHECKM_DATA_PATH` env variable. [See here](https://github.com/Ecogenomics/CheckM/wiki/Installation#required-reference-data)

2024-02-28 16:06 UTC, tonykew commented
CheckM related code removed from eb_hooks.py

2024-04-23 23:40 UTC, aebruno approved these changes

2024-04-23 23:40 UTC, merged