prokka version 1.14.5 easyconfig files
ubccr/software-layer pull request #189
Opened 2024-01-20 00:02 UTC by tonykew

prokka version 1.14.5

includes:
  tbl2asn version 20220427

Tony

2024-01-20 05:01 UTC, aebruno requested changes

2024-01-20 05:01 UTC, aebruno commented on config/easybuild/easyconfigs/tbl2asn-20220427-linux64.eb
> +postinstallcmds = [
These should be moved the eb_hooks.py and not included in the easybuild recipe.

2024-01-22 23:17 UTC, tonykew commented on config/easybuild/easyconfigs/tbl2asn-20220427-linux64.eb
> +postinstallcmds = [
libidn is a requirement for the binary - don't know why this isn't in the original easyconfig
file given there is a libidn easyconfig (which is dependent on GGCcore-11.2.0)
IMHO adding this to the easyconfig file is "the right thing to do"
...but I can more to eb_hooks.py if you don't agree,,,

2024-01-30 03:08 UTC, aebruno requested changes

2024-01-30 03:08 UTC, aebruno commented on config/easybuild/easyconfigs/tbl2asn-20220427-linux64.eb
> +    '${CCR_INIT_DIR}/easybuild/setrpaths.sh --path "%(installdir)s/bin" --add_origin --add_path="${CCR_COMPAT_PREFIX}/lib:${CCR_COMPAT_PREFIX}/lib64:${CCR_COMPAT_PREFIX}/usr/lib:${CCR_COMPAT_PREFIX}/
This line should be moved to ahook

2024-02-04 06:50 UTC, closed without merging