FSL version 6.0.5.1
ubccr/software-layer pull request #194
Opened 2024-01-26 21:17 UTC by tonykew

includes
  GLibmm version 2.66.4
  Graphviz version 8.1.0
  libsigc++ version 2.10.8
  libtool version 2.4.7
  libxml++ version 2.42.1
  mm-common version 1.0.5

Tony

2024-01-30 02:48 UTC, aebruno requested changes

2024-01-30 02:48 UTC, aebruno commented on config/easybuild/eb_hooks.py
> +             """module load libtool; """ +
This hook is not necessary. libtool is already listed in the `builddependencies` [here](https://github.com/ubccr/software-layer/pull/194/files#diff-54374902cd6891ddc22bef215de5c8633410629cfe7e3c2be4660a0d21f4ded7R27). 

The reason why it was not being loaded is because libtool is currently being filtered out as it's listed in the `filter-deps` config option [here](https://github.com/ubccr/software-layer/blob/main/config/easybuild/config.cfg#L29). 

Suggest removing libtool from `filter-deps` and remove this hook.

2024-01-31 03:01 UTC, tonykew commented on config/easybuild/eb_hooks.py
> +             """module load libtool; """ +
Sure, if you prefer.
Should be able to do that tomorrow...

2024-01-31 14:15 UTC, aebruno approved these changes

2024-01-31 14:15 UTC, merged