anvio version 7.1
ubccr/software-layer pull request #203
Opened 2024-01-31 15:38 UTC by tonykew

anvio version 7.1 easyconfig file

After install, manually run the test suite, which requires an interactive
terminal to <ctrl-c> the test server process e.g.

    $ module load gcc/11.2.0 openmpi/4.1.1 anvio/7.1-Python-3.9.6
    $ anvi-self-test --suite mini

Tony

2024-02-02 02:34 UTC, aebruno requested changes

2024-02-02 02:34 UTC, aebruno commented on config/easybuild/easyconfigs/anvio-7.1-foss-2021b-Python-3.9.6.eb
> +    ('matplotlib', '3.4.3'),
Please rebuild with `('matplotlib', '3.5.2')`. We've been using this version for all python bundles. This way there won't be a conflict when users load other bundles.

2024-02-06 20:30 UTC, tonykew commented
Rebuilt with matplotlib version 3.5.2

2024-02-09 13:44 UTC, aebruno approved these changes

2024-02-09 14:05 UTC, merged