deepTools version 3.5.1
ubccr/software-layer pull request #204
Opened 2024-01-31 22:14 UTC by tonykew

deepTools version 3.5.1 easyconfig file

Includes
  plotly.py version 5.12.0 easyconfig file

Tony

2024-02-02 02:35 UTC, aebruno requested changes

2024-02-02 02:35 UTC, aebruno commented on config/easybuild/easyconfigs/deepTools-3.5.1-foss-2021b.eb
> +    ('matplotlib', '3.4.3'),
Rebuild with `('matplotlib', '3.5.2')`

2024-02-06 19:13 UTC, tonykew commented
updated tarball:
`/srv/cosmos/mirrors/ccr/software-dev/ccr-2023.01-easybuild-tonykew_deepTools-3.5.1-foss-2021b-2024-02-06.140804.tar.gz`

2024-02-09 14:07 UTC, aebruno approved these changes

2024-02-09 14:07 UTC, merged