ont-guppy version 6.4.8
ubccr/software-layer pull request #253
Opened 2024-02-28 22:11 UTC by tonykew

ont-guppy version 6.4.8 easyconfig file

Tony

2024-03-17 04:51 UTC, aebruno requested changes

2024-03-17 04:51 UTC, aebruno commented on config/easybuild/eb_hooks.py
> +def nvidia_rpath_postproc(ec, *args, **kwargs):
This is not needed. Any easybuild recipe that contains "cuda" will automatically have this added to the rpath. [See here](https://github.com/ubccr/software-layer/blob/main/config/easybuild/eb_hooks.py#L234).

2024-03-19 14:53 UTC, tonykew commented on config/easybuild/eb_hooks.py
> +def nvidia_rpath_postproc(ec, *args, **kwargs):
eb_hooks.py code backed out

2024-03-21 13:37 UTC, aebruno approved these changes

2024-03-21 13:37 UTC, merged