IntaRNA
ubccr/software-layer pull request #292
Opened 2024-04-10 18:01 UTC by dsajdak

2024-04-17 15:18 UTC, KevinVanSlyke approved these changes
Was able to ingest tarball and run `IntaRNA --help` from $EBROOTINTARNA/bin

Review of Orca pending... Forgot about the second commit.

2024-04-17 16:14 UTC, KevinVanSlyke requested changes
The Orca files are previously committed in [PR 287](https://github.com/ubccr/software-layer/pull/287) and should be removed from this PR (292)

2024-04-17 19:00 UTC, dsajdak commented
@KevinVanSlyke sorry about that.  I fixed the PR so it only includes the intaRNA EB recipe

2024-04-18 17:43 UTC, aebruno approved these changes

2024-04-18 17:43 UTC, merged